---
epartner:
  port:
    oauth: 18080
    config: 18090
    api: 18100

  oauth:
    context-path: /
    uri: http://localhost:${epartner.port.oauth}${epartner.oauth.context-path}
    redis:
      enabled: false
      host: localhost
      port: 6379
---
spring:
  oauth2:
    resource:
      userInfoUri: ${epartner.oauth.uri}/user
  auth:
    serverurl: ${epartner.oauth.uri}/oauth/check_token
---
management:
  security:
    enabled: false
  context-path: /manage

---

mail:
  link: http://localhost:18110/#/confirmation/
   host: smtp.gmail.com
          port: 587
          username: testmaileropenfire@gmail.com
          password: Martob92*
          protocol: smtp
          tls: true
          properties.mail.smtp:
              auth: true
              starttls.enable: true
              ssl.trust: smtp.gmail.com