---
epartner:
  port:
    oauth: 18080
    config: 18090
    api: 18100

  oauth:
    context-path: /
    uri: http://localhost:${epartner.port.oauth}${epartner.oauth.context-path}
    redis:
      enabled: false
      host: localhost
      port: 6379

  images:
    url: http://localhost:18120
---
spring:
  oauth2:
    resource:
      userInfoUri: ${epartner.oauth.uri}/user
  auth:
    serverurl: ${epartner.oauth.uri}/oauth/check_token
---
management:
  security:
    enabled: false
  context-path: /manage